### ISSUE TITLE
Add the extension to the Chrome Web Store

### ISSUE THREAD

**Issue by oltoko** [kevingimbel/minute-to-hour.chrome#2]
It would be nice if the extension could be installed without using the Developer Mode.

**Comment by Haroenv** [comment]
[here](https://github.com/Haroenv/no-facebook-emojis) I used travis to make a packed extension, but I didn't put it on the store, you could use that as a reference for instructions that are basically the same, but without the `developer mode` checked.

**Comment by TimPietrusky** [comment]
+3

**Comment by KevinGimbel** [comment]
@Haroenv I didn't see your comment! I used [this guide from Google](https://developer.chrome.com/webstore/publish) to publish the extension to the Chrome Store.

In other news, it is now available on the Chrome Web Store 🎉 https://chrome.google.com/webstore/detail/minute-to-hour/obaikajlkkoedmedkglnpdailmoeaccm
